python train.py --name=parsing_net_reduc_only_text \
                --model=painet \
                --gpu_ids=0 \
                --dataroot /media/beast/WD2T/XUEYu/dataset_pose_transfer/Pose_transfer_codes/deepfashion \
                --batchSize 8 \
                --niter 1500000 \
                --display_freq 200 \
                --use_reduc_layer True \
                --use_text True \
                --mask_choice upper_clothes \
                --nThreads 2 \
                --use_masked_SPL1 False